$schema: http://json-schema.org/draft-04/schema#
id: https://github.com/datawire/pib/stack.yaml
title: Pibstack
type: object
properties:
  pibstackVersion:
    type: integer
    enum: [1]
  name:
    type: string
  image:
    type: object
    title: "Image"
    properties:
      repository:
        description: "The container image without a tag, e.g. example/myapp"
        type: string
      port:
        type: integer
    required: ["repository", "port"]
    additionalProperties: false
  expose:
    type: object
    title: "Expose"
    properties:
      path:
        type: string
    required: ["path"]
    additionalProperties: false
  requires:
    type: array
    items:
      type: object
      title: "Component"
      properties:
        type:
          type: string
          enum: ["component"]
        template:
          type: string
        config:
          type: object
        image:
          type: string
      required: ["type", "template"]
      additionalProperties: false
required: ["pibstackVersion", "image", "name"]
additionalProperties: false
