$schema: http://json-schema.org/draft-04/schema#

definitions:
  # k8s Service max == 63, currently we do service name + "---"+private
  # resource name for naming k8s Service used for private resources. Because
  # Reasons this needs to be copy/pasted, but leaving it here for documentation
  # purposes:
  name_pattern: "^[a-zA-Z][-a-zA-Z0-9]{0,29}$"

  local:
    type: object
    properties:
      templates:
        type: object
        additionalProperties: false
        patternProperties:
          "^[a-zA-Z][-a-zA-Z0-9]{0,29}$":
            oneOf:
              - $ref: "#/definitions/docker-resource"
    additionalProperties: false
    required: ["templates"]

  remote:
    type: object
    properties:
      type:
        type: string
        enum: ["kubernetes"]
      address:
        type: string
      state:
        type: string
        pattern: "^terraform:.*$"
    additionalProperties: false
    required: ["type", "address", "state"]

  docker-resource:
    type: object
    additionalProperties: false
    required: ["type", "image", "config"]
    properties:
      type:
        type: string
        enum: ["docker"]
      image:
        type: string
      config:
        type: object
        additionalProperties:
          oneOf:
            - type: string
            - type: integer
        required: ["port"]

  requires:
    type: object
    additionalProperties: false
    patternProperties:
      "^[a-zA-Z][-a-zA-Z0-9]{0,29}$":
        type: object
        properties:
          template:
            type: string
        additionalProperties: false
        required: ["template"]

  service:
    type: object
    additionalProperties: false
    required: ["image", "expose", "requires"]
    properties:
      image:
        type: object
        title: "Image"
        properties:
          repository:
            description: "The container image without a tag, e.g. example/myapp"
            type: string
          tag:
            type: string
        required: ["repository", "tag"]
        additionalProperties: false
      port:
        type: integer
      expose:
        type: object
        title: "Expose"
        properties:
          path:
            type: string
        required: ["path"]
        additionalProperties: false
      requires:
        $ref: "#/definitions/requires"


title: Envfile
type: object
properties:
  Envfile-version:
    type: integer
    enum: [1]
  local:
    $ref: "#/definitions/local"
  remote:
    $ref: "#/definitions/remote"
  application:
    type: object
    properties:
      requires:
        $ref: "#/definitions/requires"
      services:
        type: object
        patternProperties:
          "^[a-zA-Z][-a-zA-Z0-9]{0,29}$":
            $ref: "#/definitions/service"
        additionalProperties: false
    additionalProperties: false
    required: ["requires", "services"]
additionalProperties: false
required: ["Envfile-version", "application", "local"]
